### PR TITLE
Fixed "missing class type in ObjectMapper" interface

### PR DESCRIPTION
**Pull request by dewos**
Here the fix for the missing class type in the ObjectMapper interface. I added "real" Jackson @Tests (only for test scope), and updated the documentation accordingly.

### CODE REVIEW

**Comment by dewos** [comment]
ping @shashiranjan84

**Comment by danking** [comment]
Is there an ETA for merging this and pushing it to maven?

**Comment by shashiranjan84** [comment]
@danking I will try to review/merge code by this weekend

**Comment by danking** [comment]
@shashiranjan84 Awesome. Thank you very much!

**Pull request merged**
