### PR TITLE
Added support for asObject response type (serializing).

### PR DESCRIPTION
**Pull request by dewos**
Hi @thefosk, here is my contribution for your little nice library. I kept things very easy, as I too like simplicity. Have fun.

### CODE REVIEW

**Comment by dewos** [comment]
This is weird, the test passes on my system (jdk8).

**Comment by dewos** [comment]
@thefosk any news here?

**Comment by varra4u** [comment]
I like the way you plug the custom ObjectMapper into the Unireest code, but thinking of the package name you used to keep it in.

**Comment by crudbug** [comment]
:+1:

**Comment by dewos** [comment]
Well, thanks, but sadly the project seems more or less abandoned.

**Comment by sinzone** [comment]
Hi all, sorry, the project is not abandoned, we use it in production at mashape. As soon as @thefosk has a minute will check this PR.  We were fully focused on github.com/mashape/kong for the past 2 months.

**Comment by dewos** [comment]
....waiting for Godot  :)

**Comment by shashiranjan84** [comment]
@dewos why not application should handle the mapping of string to custom Objects itself as anyway they would have to provide implementation for ObjectMapper.

**Comment by dewos** [comment]
@shashiranjan84: mainly for abstraction. Oh, and convenience too (you can set the ObjectMapper, the one you like most, one time and use it everywhere without any additional line of code for each request).

**Comment by steve-taylor** [comment]
This feature is half baked at best. It assumes web services will never respond with an error. Suppose I want to fetch a `Customer` object from a web service, but the web service responds with an error and the details of the error are (obviously) in a different format than a `Customer` object. Rather than being able to handle the error, `asObject(Customer.class)` will throw an exception as the error response body cannot be deserialized into a `Customer` object. The only viable way of using this method is to call `asObject(Map.class)` and, depending on the response status code, manually convert the `Map` into a `Customer` or error object.

**Comment by dewos** [comment]
Hi @steve-taylor, php supports try catch of Exceptions, hence you could manage a custom error handler in yours ObjectMapper.

**Comment by rnc** [comment]
@dewos @steve-taylor The problem where an error is returned has been raised before in #122. The ObjectMapper does not have access to the ResponseCode so some horrible checks have to be done to see if its sane to deserialize before returning.

**Comment by dewos** [comment]
Ah yes @rnc, now I understand, I was unaware of that. Probably a middle way solution would be a change in the interface to providing the HttpResponse . Something like:

```php
public <T> T readValue(String value, Class<T> valueType, HttpResponse<T> response) {}
```

Not BC, but very easy to deal with.

**Comment by dewos** [comment]
RFC: @shashiranjan84 @rnc @steve-taylor

**Pull request merged**
