### PR TITLE
Allowing multipart field content-type and multipart entity mode

### PR DESCRIPTION
**Pull request by brothhaar**
Added HttpRequestWithBody and MultipartBody field methods with content-type to allow configuration of individual multipart fields. Also added MultipartBody mode method to allow configuration of multipart entity mode (i.e. strict vs. browser_compatible).

### CODE REVIEW

**Comment by jjwyse** [comment]
+1 bump

**Comment by brothhaar** [comment]
@thefosk Would someone mind reviewing this for inclusion in the master branch?

**Comment by brothhaar** [comment]
Never mind, I decided to fork and manage my own changes.

**Comment by thefosk** [comment]
@brothhaar Sorry I've been a little bit out of bandwidth, I'm merging this now.

**Pull request merged**
