### PR TITLE
Added File upload support using InputStream, Fixes: #91

### PR DESCRIPTION
**Pull request by varra4u**
Added File upload support using InputStream and added the relevant test cases too.

Thanks,
Rajakrishna Reddy

### CODE REVIEW

**Comment by SGrondin** [comment]
I forwarded it to the right person.

**Comment by varra4u** [comment]
Great! Actually we are using it in our project, so we were in a great need of this feature, so added. Want to see it in main code, so that we can get it from maven itself instead of having the modified code in our project.

Thank you.

**Comment by SGrondin** [comment]
It's looking good to me, I'll get back to you asap on this.

**Comment by shashiranjan84** [comment]
@varra4u Would you please update the ReadMe too?

**Comment by shashiranjan84** [comment]
@varra4u  we waiting for you to update the readme file.

**Comment by varra4u** [comment]
Hi @shashiranjan84 

I've updated the readme file, please go ahead and merge!

**Pull request merged**
