### PR TITLE
Support GET with a param which has multiple values

### PR DESCRIPTION
**Pull request by qiuxiafei**
So than we can GET like this:
```java
Unirest.get("http://httpbin.org/get").fields(new HashMap<String, Object>() {
            {
                this.put("name", Arrays.asList(0, 1, 2));
            }
        }).asJson();
```

### CODE REVIEW

**Comment by jjwyse** [comment]
Is it possible to merge this request?  The inability to pass arrays is blocking us right now and this fix is exactly what we need.

**Comment by brothhaar** [comment]
+1 for this pull request. This is a much needed feature for me.

**Comment by travismcchesney** [comment]
+1 also. I need this exact functionality in my current project. Would love to see it pulled in so I don't have to do it outside of the library.

**Comment by wyselm** [comment]
+1 could really use this capability

**Comment by sarumont** [comment]
+1

This is extremely useful for me.

**Comment by vineet-joshi** [comment]
This shit is awesome. Let's pull it in!!

**Comment by bscharm** [comment]
+1 could really use this feature! thanks

**Comment by markwilliams970** [comment]
+1 - this would really help our use case!

**Comment by ndkerby** [comment]
+1 This would really help!

**Comment by byronce** [comment]
+1 we could really use this feature!

**Comment by cephil** [comment]
+1 ditto, could use this feature!

**Comment by ramana4029** [comment]
+1 This would really help us, can you get this in

**Comment by Nijikokun** [comment]
:+1:

**Comment by thefosk** [comment]
I've decided to implement this feature by allowing to call the `field(name, value)` or `queryString(name, value)` multiple times, like:

```java
Unirest.get("http://httpbin.org/get").queryString("name", 1).queryString("name", 2).queryString("name", 3);
```

or

```java
Unirest.post("http://httpbin.org/post").field("name",1).field("name", 2).field("name", 3).asJson();
```

**Comment by jjwyse** [comment]
@thefosk - thanks, but instead of making the user go through each query parameter, check if any are a  `Collection` and then iterate through them and append them as described above, would it be possible for `UniRest` to perform this?

**Comment by thefosk** [comment]
@jjwyse available in version `1.4.1`

**Comment by qiuxiafei** [comment]
@thefosk when value of field is provided in collection style, it will make the fluent api not so fluent because user have to iterate the collection and call the `field` in a loop. It will also force users to know about the return type of the `post`  method which should be hidden perfectly. So think about it!

**Comment by jjwyse** [comment]
@qiuxiafei - I definitely agree with you on this one.  Would be really nice to handle these `Collections` in the library as opposed to the users having to do all of the work.

**Comment by thefosk** [comment]
@jjwyse @qiuxiafei As a result of this thread, this feature has already been implemented and available from version `1.4.1` (which is not the latest version anymore): https://github.com/Mashape/unirest-java/blob/master/src/main/java/com/mashape/unirest/request/HttpRequestWithBody.java#L76

**Comment by qiuxiafei** [comment]
good job @thefosk

**Comment by jjwyse** [comment]
@thefosk - Sorry, I'm probably just missing something here, but with your changes, when something like `Unirest.get(url).queryString(query)` is called, you still cannot pass in a `Collection` in the `query` map.  I see you updated the `HttpRequestWithBody` class but it seems like that object isn't used on `GET` requests.  Like I said, I could very well just be missing something here or looking at your changes incorrectly, so if that's the case, I apologize.  

I'm hoping to be able to make a `GET` request with something like `GET http://api.foo.com?bar[]=1&bar[]=2` but it seems this functionality still takes a lot of work on my end.  Thanks again.

**Comment by thefosk** [comment]
@jjwyse You're are right, I've implemented the method only for requests with a body, and not for GET requests. I just pushed a fix, and the latest version supports it.

**Comment by jjwyse** [comment]
@thefosk  - great, thanks so much - really appreciate it!

**Pull request closed without merging**
